var annotated_dup =
[
    [ "coreneuron", "namespacecoreneuron.html", "namespacecoreneuron" ],
    [ "corenrn_parameters", "classcorenrn__parameters.html", null ],
    [ "data", "structdata.html", "structdata" ],
    [ "Memb_list", "struct_memb__list.html", "struct_memb__list" ],
    [ "MemoryManaged", "class_memory_managed.html", null ],
    [ "NetCon", "struct_net_con.html", null ],
    [ "NetReceiveBuffer_t", "struct_net_receive_buffer__t.html", "struct_net_receive_buffer__t" ],
    [ "NetSendBuffer_t", "struct_net_send_buffer__t.html", "struct_net_send_buffer__t" ],
    [ "NrnCoreTransferEvents", "struct_nrn_core_transfer_events.html", "struct_nrn_core_transfer_events" ],
    [ "NrnFastImem", "struct_nrn_fast_imem.html", "struct_nrn_fast_imem" ],
    [ "NrnThread", "struct_nrn_thread.html", "struct_nrn_thread" ],
    [ "NrnThreadBAList", "struct_nrn_thread_b_a_list.html", null ],
    [ "NrnThreadMembList", "struct_nrn_thread_memb_list.html", null ],
    [ "OMP_Mutex", "class_o_m_p___mutex.html", "class_o_m_p___mutex" ],
    [ "Point_process", "struct_point__process.html", "struct_point__process" ],
    [ "PreSyn", "struct_pre_syn.html", null ],
    [ "PreSynHelper", "struct_pre_syn_helper.html", null ],
    [ "progressbar", "structprogressbar.html", "structprogressbar" ],
    [ "progressbar_time_components", "structprogressbar__time__components.html", "structprogressbar__time__components" ],
    [ "reference", "structreference.html", "structreference" ],
    [ "SetupTransferInfo", "struct_setup_transfer_info.html", "struct_setup_transfer_info" ],
    [ "ThreadDatum", "struct_thread_datum.html", "struct_thread_datum" ]
];